@Jwt = {{ LoginAPI.response.body.token }}

###
# Login
# @name LoginAPI
POST http://localhost:8000/login

{
    "email": "d@d.com",
    "password": "d"
}

###
POST  http://localhost:8000/thread
Authorization: Bearer {{Jwt}}

{
    "slug": "creating-thread-with-logged-user"
}